import type { AgentMessage } from "@earendil-works/pi-agent-core";
import type { ImageContent, Message, TextContent, ThinkingSelection, Usage } from "@earendil-works/pi-ai";
import { randomBytes, randomUUID } from "crypto";
import {
	appendFileSync,
	closeSync,
	existsSync,
	mkdirSync,
	openSync,
	readdirSync,
	readFileSync,
	readSync,
	statSync,
	writeFileSync,
} from "fs";
import { readdir } from "fs/promises";
import { join, resolve } from "path";
import { StringDecoder } from "string_decoder";
import { APP_NAME, getAgentDir as getDefaultAgentDir, getSessionsDir } from "../config.ts";
import { normalizePath, resolvePath } from "../utils/paths.ts";
import { listSessionInfos, listSessionsFromDir, type SessionListProgress } from "./session-discovery.ts";
import { type ResidentStoreStats, ResidentStringStore } from "./session-resident-store.ts";

export type { SessionListProgress } from "./session-discovery.ts";

// Fork change: inlined UUIDv7 (upstream uses the `uuid` npm package). Keeps this
// package self-contained so consumers don't need a transitive `uuid` install.
function uuidv7(): string {
	const ts = BigInt(Date.now());
	const bytes = randomBytes(10);
	const hex = [
		((ts >> 40n) & 0xffn).toString(16).padStart(2, "0"),
		((ts >> 32n) & 0xffn).toString(16).padStart(2, "0"),
		((ts >> 24n) & 0xffn).toString(16).padStart(2, "0"),
		((ts >> 16n) & 0xffn).toString(16).padStart(2, "0"),
		((ts >> 8n) & 0xffn).toString(16).padStart(2, "0"),
		(ts & 0xffn).toString(16).padStart(2, "0"),
		(0x70 | (bytes[0]! & 0x0f)).toString(16).padStart(2, "0"),
		bytes[1]!.toString(16).padStart(2, "0"),
		(0x80 | (bytes[2]! & 0x3f)).toString(16).padStart(2, "0"),
		bytes[3]!.toString(16).padStart(2, "0"),
		...Array.from(bytes.slice(4), (b) => b.toString(16).padStart(2, "0")),
	].join("");
	return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

import {
	type BashExecutionMessage,
	type ConfigurationUpdateMessage,
	type CustomMessage,
	createBranchSummaryMessage,
	createCompactionSummaryMessage,
	createCustomMessage,
} from "./messages.ts";

const contextMessageEntryIds = new WeakMap<object, string>();

/** Request-local field carried across context hooks; never persisted or sent to providers. */
export const SESSION_CONTEXT_ENTRY_ID = "__piSessionContextEntryId";

function withContextEntryId<T extends AgentMessage>(entryId: string, message: T): T {
	contextMessageEntryIds.set(message, entryId);
	return message;
}

/** Entry identity for a transient message projected from session history. */
export function getSessionContextEntryId(message: AgentMessage): string | undefined {
	return contextMessageEntryIds.get(message);
}

export interface UsageTotals {
	input: number;
	output: number;
	cacheRead: number;
	cacheWrite: number;
	cost: number;
	latestCacheHitRate: number | undefined;
}

export const CURRENT_SESSION_VERSION = 3;

export interface SessionHeader {
	type: "session";
	version?: number; // v1 sessions don't have this
	id: string;
	timestamp: string;
	cwd: string;
	parentSession?: string;
}

export interface NewSessionOptions {
	id?: string;
	parentSession?: string;
}

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel: string;
	/** Explicit selector provenance. Omitted by legacy entries and SDK-defaulted fallbacks. */
	thinkingSelection?: ThinkingSelection;
}

export interface ConfigurationUpdateEntry extends SessionEntryBase {
	type: "configuration_update";
	reasoning: { effort: string };
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	provider: string;
	modelId: string;
	/** Transient fallback changes are excluded from restored session defaults. */
	reason?: "fallback" | "fallback-revert";
	/** The model active before a fallback window, retained for restart restoration. */
	originalProvider?: string;
	originalModelId?: string;
	/** Exact selection intent; omitted by legacy histories. Machine switches do not claim ownership. */
	selectionIntent?: "configured" | "manual" | "programmatic";
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** Usage from the LLM call(s) that generated this summary, if available */
	usage?: Usage;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromHook?: boolean;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** Usage from the LLM call that generated this summary, if available */
	usage?: Usage;
	/** True if generated by an extension, false if pi-generated */
	fromHook?: boolean;
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
	type: "session_info";
	name?: string;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content is converted to a user message in buildSessionContext().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ConfigurationUpdateEntry
	| ModelChangeEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| SessionInfoEntry;

/** Raw file entry (includes header) */
export type FileEntry = SessionHeader | SessionEntry;

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
	entry: SessionEntry;
	children: SessionTreeNode[];
	/** Resolved label for this entry, if any */
	label?: string;
	/** Timestamp of the latest label change for this entry, if any */
	labelTimestamp?: string;
}

export interface SessionContext {
	messages: AgentMessage[];
	thinkingLevel: string;
	thinkingSelection?: ThinkingSelection;
	configurationUpdate?: { effort: string };
	model: { provider: string; modelId: string } | null;
}

export interface SessionInfo {
	path: string;
	id: string;
	/** Working directory where the session was started. Empty string for old sessions. */
	cwd: string;
	/** User-defined display name from session_info entries. */
	name?: string;
	/** Path to the parent session (if this session was forked). */
	parentSessionPath?: string;
	created: Date;
	modified: Date;
	messageCount: number;
	firstMessage: string;
	allMessagesText: string;
}

export type ReadonlySessionManager = Pick<
	SessionManager,
	| "getCwd"
	| "getSessionDir"
	| "getSessionId"
	| "getSessionFile"
	| "getLeafId"
	| "getLeafEntry"
	| "getEntry"
	| "getLabel"
	| "getBranch"
	| "buildContextEntries"
	| "buildSessionContext"
	| "getHeader"
	| "getEntries"
	| "getTree"
	| "getSessionName"
>;

function createSessionId(): string {
	return uuidv7();
}

export function assertValidSessionId(id: string): void {
	if (!/^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$/.test(id)) {
		throw new Error(
			"Session id must be non-empty, contain only alphanumeric characters, '-', '_', and '.', and start and end with an alphanumeric character",
		);
	}
}

/** Generate a unique short ID (8 hex chars, collision-checked) */
function generateId(byId: { has(id: string): boolean }): string {
	for (let i = 0; i < 100; i++) {
		const id = randomUUID().slice(0, 8);
		if (!byId.has(id)) return id;
	}
	// Fallback to full UUID if somehow we have collisions
	return randomUUID();
}

/** Migrate v1 → v2: add id/parentId tree structure. Mutates in place. */
function migrateV1ToV2(entries: FileEntry[]): void {
	const ids = new Set<string>();
	let prevId: string | null = null;

	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 2;
			continue;
		}

		entry.id = generateId(ids);
		entry.parentId = prevId;
		prevId = entry.id;

		// Convert firstKeptEntryIndex to firstKeptEntryId for compaction
		if (entry.type === "compaction") {
			const comp = entry as CompactionEntry & { firstKeptEntryIndex?: number };
			if (typeof comp.firstKeptEntryIndex === "number") {
				const targetEntry = entries[comp.firstKeptEntryIndex];
				if (targetEntry && targetEntry.type !== "session") {
					comp.firstKeptEntryId = targetEntry.id;
				}
				delete comp.firstKeptEntryIndex;
			}
		}
	}
}

/** Migrate v2 → v3: rename hookMessage role to custom. Mutates in place. */
function migrateV2ToV3(entries: FileEntry[]): void {
	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 3;
			continue;
		}

		// Update message entries with hookMessage role
		if (entry.type === "message") {
			const msgEntry = entry as SessionMessageEntry;
			if (msgEntry.message && (msgEntry.message as { role: string }).role === "hookMessage") {
				(msgEntry.message as { role: string }).role = "custom";
			}
		}
	}
}

/**
 * Run all necessary migrations to bring entries to current version.
 * Mutates entries in place. Returns true if any migration was applied.
 */
function migrateToCurrentVersion(entries: FileEntry[]): boolean {
	const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
	const version = header?.version ?? 1;

	if (version >= CURRENT_SESSION_VERSION) return false;

	if (version < 2) migrateV1ToV2(entries);
	if (version < 3) migrateV2ToV3(entries);

	return true;
}

/** Exported for testing */
export function migrateSessionEntries(entries: FileEntry[]): void {
	migrateToCurrentVersion(entries);
}

/** Exported for compaction.test.ts */
export function parseSessionEntries(content: string): FileEntry[] {
	const entries: FileEntry[] = [];
	const lines = content.trim().split("\n");

	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			const entry = JSON.parse(line) as FileEntry;
			entries.push(entry);
		} catch {
			// Skip malformed lines
		}
	}

	return entries;
}

export function getLatestCompactionEntry(entries: SessionEntry[]): CompactionEntry | null {
	for (let i = entries.length - 1; i >= 0; i--) {
		if (entries[i].type === "compaction") {
			return entries[i] as CompactionEntry;
		}
	}
	return null;
}

function buildEntryIndex(entries: SessionEntry[], byId?: Map<string, SessionEntry>): Map<string, SessionEntry> {
	if (byId) return byId;
	const index = new Map<string, SessionEntry>();
	for (const entry of entries) {
		index.set(entry.id, entry);
	}
	return index;
}

function buildSessionPath(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionEntry[] {
	const index = buildEntryIndex(entries, byId);
	let leaf: SessionEntry | undefined;
	if (leafId === null) {
		return [];
	}
	if (leafId) {
		leaf = index.get(leafId);
	}
	leaf ??= entries[entries.length - 1];
	if (!leaf) {
		return [];
	}

	const path: SessionEntry[] = [];
	let current: SessionEntry | undefined = leaf;
	while (current) {
		path.push(current);
		current = current.parentId ? index.get(current.parentId) : undefined;
	}
	path.reverse();
	return path;
}

function getSessionContextSettings(
	path: SessionEntry[],
): Pick<SessionContext, "thinkingLevel" | "thinkingSelection" | "configurationUpdate" | "model"> {
	let thinkingLevel = "off";
	let thinkingSelection: ThinkingSelection | undefined;
	let configurationUpdate: { effort: string } | undefined;
	let model: { provider: string; modelId: string } | null = null;
	// An explicit selection (a manual `model_change`, or the primary restored from a fallback
	// window) outranks the model id echoed by later assistant messages from the SAME provider:
	// the persisted message id is the wire id, which differs from the catalog id whenever the
	// catalog entry maps to an `upstreamModelId` (a `-fast` priority variant is the common case),
	// so trusting the echo would resume the base model and silently drop the tier. A message
	// from another provider still wins, since no `model_change` recorded that hop.
	let isModelSelectionExplicit = false;
	let isInFallbackWindow = false;
	// A fallback switch applies an ephemeral thinking level to the fallback model, so
	// the level recorded inside the window must not outlive it: restoring the primary
	// model with the fallback model's level would silently change the reasoning budget.
	// Mirrors the model restoration above, including the never-reverted (crashed) case.
	let preFallbackThinkingLevel = thinkingLevel;
	let preFallbackThinkingSelection = thinkingSelection;

	for (const entry of path) {
		if (entry.type === "thinking_level_change") {
			thinkingLevel = entry.thinkingLevel;
			thinkingSelection = entry.thinkingSelection;
		} else if (entry.type === "configuration_update") {
			configurationUpdate = { effort: entry.reasoning.effort };
		} else if (entry.type === "model_change") {
			if (entry.reason === "fallback") {
				if (!isInFallbackWindow) {
					preFallbackThinkingLevel = thinkingLevel;
					preFallbackThinkingSelection = thinkingSelection;
					if (entry.originalProvider && entry.originalModelId) {
						model = { provider: entry.originalProvider, modelId: entry.originalModelId };
						isModelSelectionExplicit = true;
					}
				}
				isInFallbackWindow = true;
			} else if (entry.reason === "fallback-revert") {
				if (isInFallbackWindow) {
					thinkingLevel = preFallbackThinkingLevel;
					thinkingSelection = preFallbackThinkingSelection;
				}
				isInFallbackWindow = false;
			} else {
				// A manual model switch abandons the window: the level the user set inside
				// it is a deliberate choice and carries over to the newly selected model.
				isInFallbackWindow = false;
				// Session files are parsed without validation, so an entry missing its provider or
				// model id must not become an authoritative selection; the fallback-original restore
				// above guards the same way, and a later assistant message still restores the model.
				if (entry.provider && entry.modelId) {
					model = { provider: entry.provider, modelId: entry.modelId };
					isModelSelectionExplicit = true;
				}
			}
		} else if (entry.type === "message" && entry.message.role === "assistant" && !isInFallbackWindow) {
			if (isModelSelectionExplicit && model?.provider === entry.message.provider) continue;
			model = { provider: entry.message.provider, modelId: entry.message.model };
			isModelSelectionExplicit = false;
		}
	}

	// The process can exit inside a fallback window; the primary model is already
	// restored above, so its pre-fallback level has to be restored with it.
	if (isInFallbackWindow) {
		thinkingLevel = preFallbackThinkingLevel;
		thinkingSelection = preFallbackThinkingSelection;
	}

	return { thinkingLevel, thinkingSelection, configurationUpdate, model };
}

/**
 * Project one selected session entry into LLM/runtime messages.
 * Plain custom entries are display/state entries and do not participate in context.
 */
export function sessionEntryToContextMessages(entry: SessionEntry): AgentMessage[] {
	if (entry.type === "message") {
		const message = entry.message;
		// Session files are parsed without validation; old versions, forks, or
		// hand-edited files can contain messages with null/missing content.
		if (
			(message.role === "user" || message.role === "assistant" || message.role === "toolResult") &&
			message.content == null
		) {
			return [withContextEntryId(entry.id, { ...message, content: [] })];
		}
		return [withContextEntryId(entry.id, message)];
	}
	if (entry.type === "configuration_update") {
		return [
			withContextEntryId(entry.id, {
				role: "configurationUpdate",
				content: [],
				effort: entry.reasoning.effort,
				timestamp: new Date(entry.timestamp).getTime(),
			} satisfies ConfigurationUpdateMessage),
		];
	}
	if (entry.type === "custom_message") {
		return [
			withContextEntryId(
				entry.id,
				createCustomMessage(entry.customType, entry.content ?? [], entry.display, entry.details, entry.timestamp),
			),
		];
	}
	if (entry.type === "branch_summary" && entry.summary) {
		return [withContextEntryId(entry.id, createBranchSummaryMessage(entry.summary, entry.fromId, entry.timestamp))];
	}
	if (entry.type === "compaction") {
		return [
			withContextEntryId(
				entry.id,
				createCompactionSummaryMessage(entry.summary, entry.tokensBefore, entry.timestamp, entry.details),
			),
		];
	}
	return [];
}

/**
 * Build the active, compaction-aware session entry list.
 *
 * This follows the current leaf path. If the path contains compaction entries,
 * the latest compaction is represented by the compaction entry itself, followed
 * by the kept entries starting at firstKeptEntryId and all entries after the
 * compaction entry. Older summarized entries are omitted.
 */
export function buildContextEntries(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionEntry[] {
	const path = buildSessionPath(entries, leafId, byId);
	let compaction: CompactionEntry | null = null;

	for (const entry of path) {
		if (entry.type === "compaction") {
			compaction = entry;
		}
	}

	if (!compaction) {
		return path;
	}

	const compactionIdx = path.findIndex((entry) => entry.id === compaction.id);
	if (compactionIdx < 0) {
		return path;
	}

	const contextEntries: SessionEntry[] = [compaction];
	let foundFirstKept = false;
	for (let i = 0; i < compactionIdx; i++) {
		const entry = path[i];
		// The latest summary supersedes every older compaction summary. Older
		// entries selected by firstKeptEntryId remain verbatim, but nesting a
		// prior summary here would double-count it in the model context.
		if (entry.type === "compaction") continue;
		if (entry.id === compaction.firstKeptEntryId) {
			foundFirstKept = true;
		}
		if (foundFirstKept) {
			contextEntries.push(entry);
		}
	}
	contextEntries.push(...path.slice(compactionIdx + 1));
	return contextEntries;
}

/**
 * Build the session context from entries using tree traversal.
 * If leafId is provided, walks from that entry to root.
 * Handles compaction and branch summaries along the path.
 */
export function buildSessionContext(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionContext {
	const path = buildSessionPath(entries, leafId, byId);
	const { thinkingLevel, thinkingSelection, model, configurationUpdate } = getSessionContextSettings(path);
	const messages = buildContextEntries(entries, leafId, byId).flatMap(sessionEntryToContextMessages);
	return { messages, thinkingLevel, thinkingSelection, model, configurationUpdate };
}

/**
 * Compute the default session directory for a cwd.
 * Encodes cwd into a safe directory name under ~/.senpi/agent/sessions/.
 */
function getDefaultSessionDirPath(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const resolvedCwd = resolvePath(cwd);
	const resolvedAgentDir = resolvePath(agentDir);
	const safePath = `--${resolvedCwd.replace(/^[/\\]/, "").replace(/[/\\:]/g, "-")}--`;
	return join(resolvedAgentDir, "sessions", safePath);
}

export function getDefaultSessionDir(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const sessionDir = getDefaultSessionDirPath(cwd, agentDir);
	if (!existsSync(sessionDir)) {
		mkdirSync(sessionDir, { recursive: true });
	}
	return sessionDir;
}

const SESSION_READ_BUFFER_SIZE = 1024 * 1024;
const SESSION_HEADER_READ_BUFFER_SIZE = 4096;
/** Bound synchronous header discovery while allowing large cwd and custom metadata fields. */
const MAX_SESSION_HEADER_SCAN_BYTES = 1024 * 1024;

class SessionHeaderScanLimitError extends Error {
	constructor(filePath: string) {
		super(`Session header exceeds ${MAX_SESSION_HEADER_SCAN_BYTES}-byte scan limit: ${filePath}`);
		this.name = "SessionHeaderScanLimitError";
	}
}

function parseSessionEntryLine(line: string): FileEntry | null {
	if (!line.trim()) return null;
	try {
		return JSON.parse(line) as FileEntry;
	} catch {
		// Skip malformed lines
		return null;
	}
}

/** Exported for testing */
export function loadEntriesFromFile(filePath: string): FileEntry[] {
	const resolvedFilePath = normalizePath(filePath);
	if (!existsSync(resolvedFilePath)) return [];

	const entries: FileEntry[] = [];
	let pending = "";
	const fd = openSync(resolvedFilePath, "r");
	try {
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_READ_BUFFER_SIZE);

		while (true) {
			const bytesRead = readSync(fd, buffer, 0, buffer.length, null);
			if (bytesRead === 0) break;

			pending += decoder.write(buffer.subarray(0, bytesRead));
			let lineStart = 0;
			let newlineIndex = pending.indexOf("\n", lineStart);
			while (newlineIndex !== -1) {
				const entry = parseSessionEntryLine(pending.slice(lineStart, newlineIndex));
				if (entry) entries.push(entry);
				lineStart = newlineIndex + 1;
				newlineIndex = pending.indexOf("\n", lineStart);
			}
			pending = pending.slice(lineStart);
		}

		pending += decoder.end();
		const finalEntry = parseSessionEntryLine(pending);
		if (finalEntry) entries.push(finalEntry);
	} finally {
		closeSync(fd);
	}

	// Validate session header before repairing the file.
	if (entries.length === 0) return entries;
	const header = entries[0];
	if (header.type !== "session" || typeof header.id !== "string") {
		return [];
	}

	return entries;
}

/**
 * Inspect a physical line while searching for the first parsed session entry.
 * Blank and malformed lines are skipped to match loadEntriesFromFile().
 * Returns undefined to keep scanning, null for a parsed non-header entry, or the header.
 */
function parseSessionHeaderCandidate(line: string): SessionHeader | null | undefined {
	if (!line.trim()) return undefined;
	const entry = parseSessionEntryLine(line);
	if (!entry) return undefined;
	if (entry.type !== "session" || typeof (entry as { id?: unknown }).id !== "string") return null;
	return entry;
}

function readSessionHeader(filePath: string): SessionHeader | null {
	const fd = openSync(filePath, "r");
	try {
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_HEADER_READ_BUFFER_SIZE);
		const lineChunks: string[] = [];
		let scannedBytes = 0;

		while (scannedBytes < MAX_SESSION_HEADER_SCAN_BYTES) {
			const readLength = Math.min(buffer.length, MAX_SESSION_HEADER_SCAN_BYTES - scannedBytes);
			const bytesRead = readSync(fd, buffer, 0, readLength, null);
			if (bytesRead === 0) {
				lineChunks.push(decoder.end());
				return parseSessionHeaderCandidate(lineChunks.join("")) ?? null;
			}
			scannedBytes += bytesRead;

			const chunk = decoder.write(buffer.subarray(0, bytesRead));
			let lineStart = 0;
			let newlineIndex = chunk.indexOf("\n", lineStart);
			while (newlineIndex !== -1) {
				lineChunks.push(chunk.slice(lineStart, newlineIndex));
				const header = parseSessionHeaderCandidate(lineChunks.join(""));
				if (header !== undefined) return header;
				lineChunks.length = 0;
				lineStart = newlineIndex + 1;
				newlineIndex = chunk.indexOf("\n", lineStart);
			}
			lineChunks.push(chunk.slice(lineStart));
		}

		// Probe for EOF so a final header without a newline is allowed when it ends
		// exactly at the scan limit. Any additional byte exceeds the bounded scan.
		const probe = Buffer.allocUnsafe(1);
		if (readSync(fd, probe, 0, probe.length, null) === 0) {
			lineChunks.push(decoder.end());
			return parseSessionHeaderCandidate(lineChunks.join("")) ?? null;
		}
		throw new SessionHeaderScanLimitError(filePath);
	} finally {
		closeSync(fd);
	}
}

function readSessionHeaderForDiscovery(filePath: string): SessionHeader | null {
	try {
		return readSessionHeader(filePath);
	} catch {
		// Discovery is best-effort: unreadable or oversized files are not sessions,
		// and one corrupt file must not prevent other sessions from being found.
		return null;
	}
}

function getSessionHeaderCwd(header: SessionHeader): string | undefined {
	const cwd = (header as { cwd?: unknown }).cwd;
	return typeof cwd === "string" ? cwd : undefined;
}

function sessionCwdMatches(cwd: string | undefined, resolvedCwd: string): boolean {
	return cwd !== undefined && cwd !== "" && resolvePath(cwd) === resolvedCwd;
}

/** Exported for testing */
export function findMostRecentSession(sessionDir: string, cwd?: string): string | null {
	const resolvedSessionDir = normalizePath(sessionDir);
	const resolvedCwd = cwd ? resolvePath(cwd) : undefined;
	try {
		const files = readdirSync(resolvedSessionDir)
			.filter((f) => f.endsWith(".jsonl"))
			.map((f) => join(resolvedSessionDir, f))
			.map((path) => ({ path, header: readSessionHeaderForDiscovery(path) }))
			.filter(
				(file): file is { path: string; header: SessionHeader } =>
					file.header !== null &&
					(!resolvedCwd || sessionCwdMatches(getSessionHeaderCwd(file.header), resolvedCwd)),
			)
			.map(({ path }) => ({ path, mtime: statSync(path).mtime }))
			.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

		return files[0]?.path || null;
	} catch {
		// Directory access and stat races make recent-session discovery unavailable.
		return null;
	}
}

/**
 * Manages conversation sessions as append-only trees stored in JSONL files.
 *
 * Each session entry has an id and parentId forming a tree structure. The "leaf"
 * pointer tracks the current position. Appending creates a child of the current leaf.
 * Branching moves the leaf to an earlier entry, allowing new branches without
 * modifying history.
 *
 * Use buildSessionContext() to get the resolved message list for the LLM, which
 * handles compaction summaries and follows the path from root to current leaf.
 */
let sessionEntryLoader = loadEntriesFromFile;

/** Test seam for observing disk reloads without mocking ESM filesystem exports. */
export function setSessionEntryLoaderForTesting(loader: typeof loadEntriesFromFile): () => void {
	const previous = sessionEntryLoader;
	sessionEntryLoader = loader;
	return () => {
		sessionEntryLoader = previous;
	};
}

export class SessionManager {
	private sessionId: string = "";
	private sessionFile: string | undefined;
	private sessionDir: string;
	private cwd: string;
	private persist: boolean;
	private flushed: boolean = false;
	private fileEntries: FileEntry[] = [];
	private byId: Map<string, SessionEntry> = new Map();
	// Runtime-only identity tracking lets AgentSession compare messages to a
	// compaction boundary by append order rather than provider timestamps.
	// Materialized persisted messages are bound as they are read; only pending
	// messages that have not reached a session entry use AgentSession's fallback.
	private entryOrdersById: Map<string, number> = new Map();
	private messageEntryPositions = new WeakMap<AgentMessage, { entryId: string; order: number }>();
	private labelsById: Map<string, string> = new Map();
	private labelTimestampsById: Map<string, string> = new Map();
	private leafId: string | null = null;
	private residentStore = new ResidentStringStore();
	private mirrorTrimmed = false;
	private compactEntriesCache: { mutation: number; entries: SessionEntry[] } | null = null;
	// Monotonic counter bumped by every mutator; memoized materialized views are
	// keyed on it so read hot paths (footer, RPC) never re-materialize unchanged sessions.
	private mutationCount = 0;
	private entriesCache: { mutation: number; entries: SessionEntry[] } | null = null;
	private branchCache: { leafId: string | null; mutation: number; entries: SessionEntry[] } | null = null;
	private sessionNameCache: string | undefined = undefined;
	// Running usage totals over ALL entries (not branch-scoped), maintained
	// incrementally on assistant-message append and rebuilt from scratch in
	// _buildIndex()/newSession. Usage fields are numeric and unaffected by
	// string externalization, so the resident form can be read directly.
	private usageTotals: UsageTotals = {
		input: 0,
		output: 0,
		cacheRead: 0,
		cacheWrite: 0,
		cost: 0,
		latestCacheHitRate: undefined,
	};

	private constructor(
		cwd: string,
		sessionDir: string,
		sessionFile: string | undefined,
		persist: boolean,
		newSessionOptions?: NewSessionOptions,
		preloadedFileEntries?: FileEntry[],
	) {
		this.cwd = resolvePath(cwd);
		this.sessionDir = normalizePath(sessionDir);
		this.persist = persist;
		if (persist && this.sessionDir && !existsSync(this.sessionDir)) {
			mkdirSync(this.sessionDir, { recursive: true });
		}

		if (sessionFile) {
			this._setSessionFile(sessionFile, preloadedFileEntries);
		} else {
			this.newSession(newSessionOptions);
		}
	}

	/**
	 * Reload session entries from the session file on disk.
	 */
	reloadFromDisk(): void {
		if (!this.sessionFile || !existsSync(this.sessionFile)) return;

		// A live session file can be observed between truncate and rewrite. Treat
		// that window (and an invalid replacement) as unavailable rather than
		// routing it through the create/recover path in _setSessionFile().
		const fileEntries = loadEntriesFromFile(this.sessionFile);
		if (fileEntries.length === 0) {
			if (statSync(this.sessionFile).size === 0) return;
			throw new Error(`Session file is not a valid ${APP_NAME} session: ${this.sessionFile}`);
		}
		this._setSessionFile(this.sessionFile, fileEntries);
	}

	/** Switch to a different session file (used for resume and branching) */
	setSessionFile(sessionFile: string): void {
		this._setSessionFile(sessionFile);
	}

	private _setSessionFile(sessionFile: string, preloadedFileEntries?: FileEntry[]): void {
		this.sessionFile = resolvePath(sessionFile);
		this.mirrorTrimmed = false;
		this.residentStore.clear();
		if (existsSync(this.sessionFile)) {
			this.fileEntries = preloadedFileEntries ?? loadEntriesFromFile(this.sessionFile);

			// If file was empty, initialize it with a valid session header. If it was
			// non-empty but did not parse as a pi session, fail without modifying it.
			if (this.fileEntries.length === 0) {
				const explicitPath = this.sessionFile;
				if (statSync(explicitPath).size > 0) {
					throw new Error(`Session file is not a valid ${APP_NAME} session: ${explicitPath}`);
				}
				this.newSession();
				this.sessionFile = explicitPath;
				this._rewriteFile();
				this.flushed = true;
				return;
			}

			const header = this.fileEntries.find((e) => e.type === "session") as SessionHeader | undefined;
			this.sessionId = header?.id ?? createSessionId();

			if (migrateToCurrentVersion(this.fileEntries)) {
				this._rewriteFile();
			}

			this.fileEntries = this.fileEntries.map((entry) => this.residentStore.externalize(entry));
			this._buildIndex();
			this.mutationCount++;
			this.flushed = true;
		} else {
			const explicitPath = this.sessionFile;
			this.newSession();
			this.sessionFile = explicitPath; // preserve explicit path from --session flag
		}
	}

	newSession(options?: NewSessionOptions): string | undefined {
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		this.sessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: this.sessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: options?.parentSession,
		};
		this.fileEntries = [header];
		this.mirrorTrimmed = false;
		this.residentStore.clear();
		this.byId.clear();
		this.entryOrdersById.clear();
		this.messageEntryPositions = new WeakMap();
		this.labelsById.clear();
		this.labelTimestampsById.clear();
		this.leafId = null;
		this.sessionNameCache = undefined;
		this.usageTotals = {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
			cost: 0,
			latestCacheHitRate: undefined,
		};
		this.mutationCount++;
		this.flushed = false;

		if (this.persist) {
			const fileTimestamp = timestamp.replace(/[:.]/g, "-");
			this.sessionFile = join(this.getSessionDir(), `${fileTimestamp}_${this.sessionId}.jsonl`);
		}
		return this.sessionFile;
	}

	private _buildIndex(): void {
		this.byId.clear();
		this.entryOrdersById.clear();
		this.messageEntryPositions = new WeakMap();
		this.labelsById.clear();
		this.labelTimestampsById.clear();
		this.leafId = null;
		this.sessionNameCache = undefined;
		this.usageTotals = {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
			cost: 0,
			latestCacheHitRate: undefined,
		};
		for (const [order, entry] of this.fileEntries.entries()) {
			if (entry.type === "session") continue;
			this.byId.set(entry.id, entry);
			this.entryOrdersById.set(entry.id, order);
			this.leafId = entry.id;
			this._accumulateUsage(entry);
			if (entry.type === "session_info") {
				// Empty names explicitly clear the session title.
				this.sessionNameCache = entry.name?.trim() || undefined;
			}
			if (entry.type === "label") {
				if (entry.label) {
					this.labelsById.set(entry.targetId, entry.label);
					this.labelTimestampsById.set(entry.targetId, entry.timestamp);
				} else {
					this.labelsById.delete(entry.targetId);
					this.labelTimestampsById.delete(entry.targetId);
				}
			}
		}
	}

	private _rewriteFile(): void {
		if (!this.persist || !this.sessionFile) return;
		const fd = openSync(this.sessionFile, "w");
		try {
			for (const entry of this.fileEntries) {
				writeFileSync(fd, `${JSON.stringify(this.residentStore.materialize(entry))}\n`);
			}
		} finally {
			closeSync(fd);
		}
	}

	isPersisted(): boolean {
		return this.persist;
	}

	getCwd(): string {
		return this.cwd;
	}

	getSessionDir(): string {
		return this.sessionDir;
	}

	usesDefaultSessionDir(): boolean {
		return this.sessionDir === getDefaultSessionDirPath(this.cwd);
	}

	getSessionId(): string {
		return this.sessionId;
	}

	getSessionFile(): string | undefined {
		return this.sessionFile;
	}

	getResidentStoreStats(): ResidentStoreStats {
		return this.residentStore.stats();
	}

	_persist(entry: SessionEntry): void {
		if (!this.persist || !this.sessionFile) return;
		const persistedEntry = this.residentStore.materialize(entry);

		const hasAssistant = this.fileEntries.some((e) => e.type === "message" && e.message.role === "assistant");
		// A deliberate model choice is meaningful session state even before the first assistant
		// response. Persist it immediately so reopening an otherwise empty conversation does not
		// silently turn the user's override back into policy ownership.
		if (!hasAssistant && !(entry.type === "model_change" && entry.selectionIntent === "manual")) {
			if (this.flushed) {
				appendFileSync(this.sessionFile, `${JSON.stringify(persistedEntry)}\n`);
			} else {
				// Mark as not flushed so when assistant arrives, all entries get written
				this.flushed = false;
			}
			return;
		}

		if (!this.flushed) {
			const fd = openSync(this.sessionFile, "wx");
			try {
				for (const e of this.fileEntries) {
					writeFileSync(fd, `${JSON.stringify(this.residentStore.materialize(e))}\n`);
				}
			} finally {
				closeSync(fd);
			}
			this.flushed = true;
		} else {
			appendFileSync(this.sessionFile, `${JSON.stringify(persistedEntry)}\n`);
		}
	}

	private _appendEntry(entry: SessionEntry): void {
		const residentEntry = this.residentStore.externalize(entry);
		this.fileEntries.push(residentEntry);
		this.byId.set(residentEntry.id, residentEntry);
		this.entryOrdersById.set(residentEntry.id, this.fileEntries.length - 1);
		this.leafId = residentEntry.id;
		this._accumulateUsage(residentEntry);
		this.mutationCount++;
		this._persist(residentEntry);
	}

	/**
	 * Append an already-materialized entry without rewriting its identity or tree
	 * fields. This is the transport seam for entries captured by another manager.
	 */
	appendEntry(entry: SessionEntry): void {
		this._appendEntry(entry);
		const order = this.entryOrdersById.get(entry.id);
		if (entry.type === "message" && order !== undefined) {
			this.messageEntryPositions.set(entry.message, { entryId: entry.id, order });
		}
		if (entry.type === "session_info") this.sessionNameCache = entry.name?.trim() || undefined;
		if (entry.type === "label") {
			if (entry.label) {
				this.labelsById.set(entry.targetId, entry.label);
				this.labelTimestampsById.set(entry.targetId, entry.timestamp);
			} else {
				this.labelsById.delete(entry.targetId);
				this.labelTimestampsById.delete(entry.targetId);
			}
		}
	}

	private _materializeEntry(entry: SessionEntry): SessionEntry {
		let missingResidentString = false;
		const materialized = this.residentStore.materialize(entry, () => {
			missingResidentString = true;
			return undefined;
		});
		// The resident store is a bounded cache. The JSONL remains authoritative
		// when an evicted blob is needed by a branch or read operation.
		if (missingResidentString && this.sessionFile) {
			const persisted = loadEntriesFromFile(this.sessionFile).find((candidate) => candidate.id === entry.id);
			if (persisted) return persisted as SessionEntry;
		}
		if (materialized.type === "message") {
			const order = this.entryOrdersById.get(materialized.id);
			if (order !== undefined) {
				this.messageEntryPositions.set(materialized.message, { entryId: materialized.id, order });
			}
		}
		return materialized;
	}

	/**
	 * Fold one entry into the running usage totals. Totals iterate ALL entries
	 * (not branch-scoped), matching the footer hot path's historical semantics.
	 */
	private _accumulateUsage(entry: SessionEntry): void {
		if (entry.type !== "message" || entry.message.role !== "assistant") return;
		const usage = entry.message.usage;
		// Assistant messages persisted without usage (e.g. aborted/error turns in
		// older session files) contribute nothing to the running totals.
		if (!usage) return;
		this.usageTotals.input += usage.input;
		this.usageTotals.output += usage.output;
		this.usageTotals.cacheRead += usage.cacheRead;
		this.usageTotals.cacheWrite += usage.cacheWrite;
		this.usageTotals.cost += usage.cost?.total ?? 0;
		const latestPromptTokens = usage.input + usage.cacheRead + usage.cacheWrite;
		this.usageTotals.latestCacheHitRate =
			latestPromptTokens > 0 ? (usage.cacheRead / latestPromptTokens) * 100 : undefined;
	}

	/**
	 * O(1) running usage totals across ALL session entries (not branch-scoped).
	 * Maintained incrementally; identical to summing usage over getEntries().
	 */
	getUsageTotals(): UsageTotals {
		return this.usageTotals;
	}

	/** Append a message as child of current leaf, then advance leaf. Returns entry id.
	 * Does not allow writing CompactionSummaryMessage and BranchSummaryMessage directly.
	 * Reason: we want these to be top-level entries in the session, not message session entries,
	 * so it is easier to find them.
	 * These need to be appended via appendCompaction() and appendBranchSummary() methods.
	 */
	appendMessage(message: Message | CustomMessage | BashExecutionMessage): string {
		const entry: SessionMessageEntry = {
			type: "message",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			message,
		};
		this._appendEntry(entry);
		const order = this.entryOrdersById.get(entry.id);
		if (order !== undefined) {
			this.messageEntryPositions.set(message, { entryId: entry.id, order });
		}
		return entry.id;
	}

	/** Runtime append position for this exact persisted message object, if known. */
	getMessageEntryPosition(message: AgentMessage): Readonly<{ entryId: string; order: number }> | undefined {
		return this.messageEntryPositions.get(message);
	}

	/** Runtime/file append position for an entry, used with getMessageEntryPosition(). */
	getEntryOrder(entryId: string): number | undefined {
		return this.entryOrdersById.get(entryId);
	}

	/** Append a thinking level change as child of current leaf, then advance leaf. Returns entry id. */
	appendThinkingLevelChange(thinkingLevel: string, thinkingSelection?: ThinkingSelection): string {
		const entry: ThinkingLevelChangeEntry = {
			type: "thinking_level_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			thinkingLevel,
			thinkingSelection,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a durable Responses configuration update as child of current leaf. */
	appendConfigurationUpdate(effort: string): string {
		const entry: ConfigurationUpdateEntry = {
			type: "configuration_update",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			reasoning: { effort },
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a model change as child of current leaf, then advance leaf. Returns entry id. */
	appendModelChange(
		provider: string,
		modelId: string,
		reason?: "fallback" | "fallback-revert",
		originalProvider?: string,
		originalModelId?: string,
		selectionIntent?: ModelChangeEntry["selectionIntent"],
	): string {
		const entry: ModelChangeEntry = {
			type: "model_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			provider,
			modelId,
			reason,
			originalProvider,
			originalModelId,
			selectionIntent,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a compaction summary as child of current leaf, then advance leaf. Returns entry id. */
	appendCompaction<T = unknown>(
		summary: string,
		firstKeptEntryId: string,
		tokensBefore: number,
		details?: T,
		fromHook?: boolean,
		usage?: Usage,
	): string {
		const entry: CompactionEntry<T> = {
			type: "compaction",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			summary,
			firstKeptEntryId,
			tokensBefore,
			details,
			usage,
			fromHook,
		};
		this._appendEntry(entry);
		this._trimMirrorAfterCompaction(entry);
		return entry.id;
	}

	private _trimMirrorAfterCompaction(compaction: CompactionEntry): void {
		if (!this.persist) return;
		const firstKeptIndex = this.fileEntries.findIndex((entry) => entry.id === compaction.firstKeptEntryId);
		const compactionIndex = this.fileEntries.findIndex((entry) => entry.id === compaction.id);
		if (firstKeptIndex < 0 || compactionIndex < firstKeptIndex) return;

		const header = this.fileEntries.find((entry) => entry.type === "session");
		const retained = [
			...this.fileEntries.slice(0, firstKeptIndex).filter((entry) => entry.type !== "message"),
			...this.fileEntries.slice(firstKeptIndex, compactionIndex + 1),
		];
		let parentId: string | null = null;
		for (const entry of retained) {
			if (entry.type !== "session") entry.parentId = parentId;
			parentId = entry.type === "session" ? null : entry.id;
		}
		this.residentStore.clear();
		this.mirrorTrimmed = true;
		this.fileEntries = [header, ...retained]
			.filter((entry): entry is FileEntry => entry !== undefined)
			.map((entry) => this.residentStore.externalize(entry));
		this._buildIndex();
		this.mutationCount++;
	}

	/** Append a custom entry (for extensions) as child of current leaf, then advance leaf. */
	appendCustomEntry(customType: string, data?: unknown): string {
		const entry: CustomEntry = {
			type: "custom",
			customType,
			data,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a session info entry (e.g., display name). Returns entry id. */
	appendSessionInfo(name: string): string {
		const sanitizedName = name.replace(/[\r\n]+/g, " ").trim();
		const entry: SessionInfoEntry = {
			type: "session_info",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			name: sanitizedName,
		};
		this.sessionNameCache = sanitizedName || undefined;
		this._appendEntry(entry);
		return entry.id;
	}

	/**
	 * Get the current session name from the latest session_info entry, if any.
	 * O(1): the value is maintained incrementally on appendSessionInfo() and index rebuilds.
	 */
	getSessionName(): string | undefined {
		return this.sessionNameCache;
	}

	/**
	 * Append a custom message entry (for extensions) that participates in LLM context.
	 * @param customType Extension identifier for filtering on reload
	 * @param content Message content (string or TextContent/ImageContent array)
	 * @param display Whether to show in TUI (true = styled display, false = hidden)
	 * @param details Optional extension-specific metadata (not sent to LLM)
	 * @returns Entry id
	 */
	appendCustomMessageEntry<T = unknown>(
		customType: string,
		content: string | (TextContent | ImageContent)[],
		display: boolean,
		details?: T,
	): string {
		const entry: CustomMessageEntry<T> = {
			type: "custom_message",
			customType,
			content,
			display,
			details,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	// =========================================================================
	// Tree Traversal
	// =========================================================================

	getLeafId(): string | null {
		return this.leafId;
	}

	getLeafEntry(): SessionEntry | undefined {
		const entry = this.leafId ? this.byId.get(this.leafId) : undefined;
		return entry ? this._materializeEntry(entry) : undefined;
	}

	getEntry(id: string): SessionEntry | undefined {
		const entry = this.byId.get(id);
		if (entry) return this._materializeEntry(entry);
		if (this.mirrorTrimmed && this.sessionFile) {
			const persisted = this._loadFullHistoryEntries().find((candidate) => candidate.id === id);
			return persisted ? (this.residentStore.materialize(persisted) as SessionEntry) : undefined;
		}
		return undefined;
	}

	/**
	 * Get all direct children of an entry.
	 */
	getChildren(parentId: string): SessionEntry[] {
		const children: SessionEntry[] = [];
		for (const entry of this.byId.values()) {
			if (entry.parentId === parentId) {
				children.push(this._materializeEntry(entry));
			}
		}
		return children;
	}

	/**
	 * Get the label for an entry, if any.
	 */
	getLabel(id: string): string | undefined {
		return this.labelsById.get(id);
	}

	/**
	 * Set or clear a label on an entry.
	 * Labels are user-defined markers for bookmarking/navigation.
	 * Pass undefined or empty string to clear the label.
	 */
	appendLabelChange(targetId: string, label: string | undefined): string {
		if (!this.byId.has(targetId)) {
			throw new Error(`Entry ${targetId} not found`);
		}
		const entry: LabelEntry = {
			type: "label",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			targetId,
			label,
		};
		this._appendEntry(entry);
		if (label) {
			this.labelsById.set(targetId, label);
			this.labelTimestampsById.set(targetId, entry.timestamp);
		} else {
			this.labelsById.delete(targetId);
			this.labelTimestampsById.delete(targetId);
		}
		return entry.id;
	}

	/**
	 * Walk from entry to root, returning all entries in path order.
	 * Includes all entry types (messages, compaction, model changes, etc.).
	 * Use buildSessionContext() to get the resolved messages for the LLM.
	 */
	getBranch(fromId?: string): SessionEntry[] {
		// No-arg reads (the common hot path) are memoized on (leafId, mutationCount);
		// explicit fromId lookups bypass the cache.
		if (
			fromId === undefined &&
			this.branchCache !== null &&
			this.branchCache.leafId === this.leafId &&
			this.branchCache.mutation === this.mutationCount
		) {
			return this.branchCache.entries;
		}
		const path: SessionEntry[] = [];
		const startId = fromId ?? this.leafId;
		let entriesById = this.byId;
		if (fromId !== undefined && !entriesById.has(fromId) && this.mirrorTrimmed && this.sessionFile) {
			entriesById = new Map(
				this._loadFullHistoryEntries()
					.filter((entry) => entry.type !== "session")
					.map((entry) => [entry.id, this.residentStore.materialize(entry) as SessionEntry]),
			);
		}
		let current = startId ? entriesById.get(startId) : undefined;
		while (current) {
			path.unshift(this._materializeEntry(current));
			current = current.parentId ? entriesById.get(current.parentId) : undefined;
		}
		if (fromId === undefined) {
			this.branchCache = { leafId: this.leafId, mutation: this.mutationCount, entries: path };
		}
		return path;
	}

	/**
	 * Build the active, compaction-aware entry list for context/rendering.
	 * Uses tree traversal from current leaf.
	 */
	buildContextEntries(): SessionEntry[] {
		return buildContextEntries(this._getCompactEntries(), this.leafId);
	}

	/**
	 * Build the session context (what gets sent to the LLM).
	 * Uses tree traversal from current leaf.
	 */
	buildSessionContext(): SessionContext {
		return buildSessionContext(this._getCompactEntries(), this.leafId);
	}

	hasContextMessages(): boolean {
		return this.hasBranchEntry(
			(entry) =>
				entry.type === "message" ||
				entry.type === "custom_message" ||
				entry.type === "compaction" ||
				(entry.type === "branch_summary" && Boolean(entry.summary)),
		);
	}

	hasThinkingLevelChanges(): boolean {
		return this.hasBranchEntry((entry) => entry.type === "thinking_level_change");
	}

	countCompactions(): number {
		let count = 0;
		for (const entry of this.fileEntries) {
			if (entry.type === "compaction") count++;
		}
		return count;
	}

	private hasBranchEntry(predicate: (entry: SessionEntry) => boolean): boolean {
		let current = this.leafId ? this.byId.get(this.leafId) : undefined;
		while (current) {
			if (predicate(current)) return true;
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
		return false;
	}

	/**
	 * Get session header.
	 */
	getHeader(): SessionHeader | null {
		const h = this.fileEntries.find((e) => e.type === "session");
		return h ? this.residentStore.materialize(h as SessionHeader) : null;
	}

	/**
	 * Get all session entries (excludes header).
	 * The session is append-only: use appendXXX() to add entries, branch() to
	 * change the leaf pointer. Entries cannot be modified or deleted.
	 *
	 * The result is memoized behind the session mutation counter: repeated calls
	 * without an intervening mutation return the SAME shared array instance.
	 * Callers must not mutate the returned array or its entries; copy first if
	 * you need to filter/reorder.
	 */
	getEntries(): SessionEntry[] {
		if (this.mirrorTrimmed && this.sessionFile) {
			return this._loadFullHistoryEntries()
				.filter((e): e is SessionEntry => e.type !== "session")
				.map((entry) => this.residentStore.materialize(entry));
		}
		if (this.entriesCache !== null && this.entriesCache.mutation === this.mutationCount) {
			return this.entriesCache.entries;
		}
		const entries = this.fileEntries
			.filter((e): e is SessionEntry => e.type !== "session")
			.map((entry) => this._materializeEntry(entry));
		this.entriesCache = { mutation: this.mutationCount, entries };
		return entries;
	}

	private _getCompactEntries(): SessionEntry[] {
		if (this.compactEntriesCache?.mutation !== this.mutationCount) {
			this.compactEntriesCache = {
				mutation: this.mutationCount,
				entries: this.fileEntries.filter((e): e is SessionEntry => e.type !== "session"),
			};
		}

		const entries = this.compactEntriesCache.entries;
		const missingEntryIds = new Set<string>();
		for (const entry of entries) {
			this.residentStore.materialize(entry, () => {
				missingEntryIds.add(entry.id);
				return undefined;
			});
		}
		if (missingEntryIds.size > 0 && this.sessionFile) {
			const persistedById = new Map(this._loadFullHistoryEntries().map((entry) => [entry.id, entry]));
			for (let index = 0; index < entries.length; index++) {
				const entry = entries[index]!;
				if (!missingEntryIds.has(entry.id)) continue;
				const persisted = persistedById.get(entry.id);
				if (persisted) entries[index] = this.residentStore.externalize(persisted) as SessionEntry;
			}
		}
		const materialized = entries.map((entry) => this.residentStore.materialize(entry) as SessionEntry);
		for (const entry of materialized) {
			if (entry.type !== "message") continue;
			const order = this.entryOrdersById.get(entry.id);
			if (order !== undefined) this.messageEntryPositions.set(entry.message, { entryId: entry.id, order });
		}
		return materialized;
	}

	private _loadFullHistoryEntries(): FileEntry[] {
		return this.sessionFile ? sessionEntryLoader(this.sessionFile) : this.fileEntries;
	}

	/**
	 * Get the session as a tree structure. Returns a shallow defensive copy of all entries.
	 * A well-formed session has exactly one root (first entry with parentId === null).
	 * Orphaned entries (broken parent chain) are also returned as roots.
	 */
	getTree(): SessionTreeNode[] {
		const entries = this.getEntries();
		const nodeMap = new Map<string, SessionTreeNode>();
		const roots: SessionTreeNode[] = [];

		// Create nodes with resolved labels
		for (const entry of entries) {
			const label = this.labelsById.get(entry.id);
			const labelTimestamp = this.labelTimestampsById.get(entry.id);
			nodeMap.set(entry.id, { entry, children: [], label, labelTimestamp });
		}

		// Build tree
		for (const entry of entries) {
			const node = nodeMap.get(entry.id)!;
			if (entry.parentId === null || entry.parentId === entry.id) {
				roots.push(node);
			} else {
				const parent = nodeMap.get(entry.parentId);
				if (parent) {
					parent.children.push(node);
				} else {
					// Orphan - treat as root
					roots.push(node);
				}
			}
		}

		// Sort children by timestamp (oldest first, newest at bottom)
		// Use iterative approach to avoid stack overflow on deep trees
		const stack: SessionTreeNode[] = [...roots];
		while (stack.length > 0) {
			const node = stack.pop()!;
			node.children.sort((a, b) => new Date(a.entry.timestamp).getTime() - new Date(b.entry.timestamp).getTime());
			stack.push(...node.children);
		}

		return roots;
	}

	// =========================================================================
	// Branching
	// =========================================================================

	/**
	 * Start a new branch from an earlier entry.
	 * Moves the leaf pointer to the specified entry. The next appendXXX() call
	 * will create a child of that entry, forming a new branch. Existing entries
	 * are not modified or deleted.
	 */
	branch(branchFromId: string): void {
		if (!this.byId.has(branchFromId) && this.sessionFile) {
			this.reloadFromDisk();
		}
		if (!this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
		this.mutationCount++;
	}

	/**
	 * Reset the leaf pointer to null (before any entries).
	 * The next appendXXX() call will create a new root entry (parentId = null).
	 * Use this when navigating to re-edit the first user message.
	 */
	resetLeaf(): void {
		this.leafId = null;
		this.mutationCount++;
	}

	/**
	 * Start a new branch with a summary of the abandoned path.
	 * Same as branch(), but also appends a branch_summary entry that captures
	 * context from the abandoned conversation path.
	 */
	branchWithSummary(
		branchFromId: string | null,
		summary: string,
		details?: unknown,
		fromHook?: boolean,
		usage?: Usage,
	): string {
		if (branchFromId !== null && !this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		const fromId = this.leafId ?? "root";
		this.leafId = branchFromId;
		const entry: BranchSummaryEntry = {
			type: "branch_summary",
			id: generateId(this.byId),
			parentId: branchFromId,
			timestamp: new Date().toISOString(),
			fromId,
			summary,
			details,
			usage,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/**
	 * Create a new session file containing only the path from root to the specified leaf.
	 * Useful for extracting a single conversation path from a branched session.
	 * Returns the new session file path, or undefined if not persisting.
	 */
	createBranchedSession(leafId: string): string | undefined {
		const previousSessionFile = this.sessionFile;
		const path = this.getBranch(leafId);
		if (path.length === 0) {
			throw new Error(`Entry ${leafId} not found`);
		}

		// Filter out LabelEntry from path - we'll recreate them from the resolved map.
		// Because labels are real tree entries, later entries can be children of labels;
		// removing labels requires re-chaining the retained path to avoid orphaned subtrees.
		const pathWithoutLabels: SessionEntry[] = [];
		let pathParentId: string | null = null;
		for (const entry of path) {
			if (entry.type === "label") continue;
			pathWithoutLabels.push({ ...entry, parentId: pathParentId });
			pathParentId = entry.id;
		}

		const newSessionId = createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(this.getSessionDir(), `${fileTimestamp}_${newSessionId}.jsonl`);

		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: this.persist ? previousSessionFile : undefined,
		};

		// Collect labels for entries in the path
		const pathEntryIds = new Set(pathWithoutLabels.map((e) => e.id));
		const labelsToWrite: Array<{ targetId: string; label: string; timestamp: string }> = [];
		for (const [targetId, label] of this.labelsById) {
			if (pathEntryIds.has(targetId)) {
				labelsToWrite.push({ targetId, label, timestamp: this.labelTimestampsById.get(targetId)! });
			}
		}

		if (this.persist) {
			// Build label entries
			const lastEntryId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
			let parentId = lastEntryId;
			const labelEntries: LabelEntry[] = [];
			for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
				const labelEntry: LabelEntry = {
					type: "label",
					id: generateId(new Set(pathEntryIds)),
					parentId,
					timestamp: labelTimestamp,
					targetId,
					label,
				};
				pathEntryIds.add(labelEntry.id);
				labelEntries.push(labelEntry);
				parentId = labelEntry.id;
			}

			this.residentStore.clear();
			this.mirrorTrimmed = false;
			this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries].map((entry) =>
				this.residentStore.externalize(entry),
			);
			this.sessionId = newSessionId;
			this.sessionFile = newSessionFile;
			this._buildIndex();
			this.mutationCount++;

			// Only write the file now if it contains an assistant message.
			// Otherwise defer to _persist(), which creates the file on the
			// first assistant response, matching the newSession() contract
			// and avoiding the duplicate-header bug when _persist()'s
			// no-assistant guard later resets flushed to false.
			const hasAssistant = this.fileEntries.some((e) => e.type === "message" && e.message.role === "assistant");
			if (hasAssistant) {
				this._rewriteFile();
				this.flushed = true;
			} else {
				this.flushed = false;
			}

			return newSessionFile;
		}

		// In-memory mode: replace current session with the path + labels
		const labelEntries: LabelEntry[] = [];
		let parentId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
		for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
			const labelEntry: LabelEntry = {
				type: "label",
				id: generateId(new Set([...pathEntryIds, ...labelEntries.map((e) => e.id)])),
				parentId,
				timestamp: labelTimestamp,
				targetId,
				label,
			};
			labelEntries.push(labelEntry);
			parentId = labelEntry.id;
		}
		this.residentStore.clear();
		this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries].map((entry) =>
			this.residentStore.externalize(entry),
		);
		this.sessionId = newSessionId;
		this._buildIndex();
		this.mutationCount++;
		return undefined;
	}

	/**
	 * Create a new session.
	 * @param cwd Working directory (stored in session header)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.senpi/agent/sessions/<encoded-cwd>/).
	 */
	static create(cwd: string, sessionDir?: string, options?: NewSessionOptions): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		return new SessionManager(cwd, dir, undefined, true, options);
	}

	/**
	 * Open a specific session file.
	 * @param path Path to session file
	 * @param sessionDir Optional session directory for /new or /branch. If omitted, derives from file's parent.
	 * @param cwdOverride Optional cwd override instead of the session header cwd.
	 */
	static open(path: string, sessionDir?: string, cwdOverride?: string): SessionManager {
		const resolvedPath = resolvePath(path);
		let header: SessionHeader | null = null;
		let preloadedFileEntries: FileEntry[] | undefined;
		if (cwdOverride === undefined && existsSync(resolvedPath)) {
			try {
				header = readSessionHeader(resolvedPath);
			} catch (error) {
				if (!(error instanceof SessionHeaderScanLimitError)) throw error;
				// The bounded scan is only a discovery optimization. A full load remains
				// authoritative for legacy files with very large headers or prefixes.
				preloadedFileEntries = loadEntriesFromFile(resolvedPath);
				const firstEntry = preloadedFileEntries[0];
				header = firstEntry?.type === "session" ? firstEntry : null;
			}
		}
		// This process opens the session for append; normalize a final unterminated
		// JSONL entry here, never from read-only loadEntriesFromFile callers.
		if (existsSync(resolvedPath)) {
			const content = readFileSync(resolvedPath);
			if (content.length > 0 && content[content.length - 1] !== 10) appendFileSync(resolvedPath, "\n");
		}
		const cwd = cwdOverride ?? (header ? getSessionHeaderCwd(header) : undefined) ?? process.cwd();
		// If no sessionDir provided, derive from file's parent directory
		const dir = sessionDir ? normalizePath(sessionDir) : resolve(resolvedPath, "..");
		return new SessionManager(cwd, dir, resolvedPath, true, undefined, preloadedFileEntries);
	}

	/**
	 * Continue the most recent session, or create new if none.
	 * @param cwd Working directory
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.senpi/agent/sessions/<encoded-cwd>/).
	 */
	static continueRecent(cwd: string, sessionDir?: string): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const mostRecent = findMostRecentSession(dir, filterCwd ? cwd : undefined);
		if (mostRecent) {
			return new SessionManager(cwd, dir, mostRecent, true);
		}
		return new SessionManager(cwd, dir, undefined, true);
	}

	/** Create an in-memory session (no file persistence) */
	static inMemory(cwd: string = process.cwd(), options?: NewSessionOptions): SessionManager {
		return new SessionManager(cwd, "", undefined, false, options);
	}

	/**
	 * Fork a session from another project directory into the current project.
	 * Creates a new session in the target cwd with the full history from the source session.
	 * @param sourcePath Path to the source session file
	 * @param targetCwd Target working directory (where the new session will be stored)
	 * @param sessionDir Optional session directory. If omitted, uses default for targetCwd.
	 */
	static forkFrom(
		sourcePath: string,
		targetCwd: string,
		sessionDir?: string,
		options?: NewSessionOptions,
	): SessionManager {
		const resolvedSourcePath = resolvePath(sourcePath);
		const resolvedTargetCwd = resolvePath(targetCwd);
		const sourceEntries = loadEntriesFromFile(resolvedSourcePath);
		if (sourceEntries.length === 0) {
			throw new Error(`Cannot fork: source session file is empty or invalid: ${resolvedSourcePath}`);
		}

		const sourceHeader = sourceEntries.find((e) => e.type === "session") as SessionHeader | undefined;
		if (!sourceHeader) {
			throw new Error(`Cannot fork: source session has no header: ${resolvedSourcePath}`);
		}

		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(resolvedTargetCwd);
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		// Create new session file with new ID but forked content
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		const newSessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(dir, `${fileTimestamp}_${newSessionId}.jsonl`);

		// Write new header pointing to source as parent, with updated cwd
		const newHeader: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: resolvedTargetCwd,
			parentSession: resolvedSourcePath,
		};
		writeFileSync(newSessionFile, `${JSON.stringify(newHeader)}\n`, { flag: "wx" });

		// Copy all non-header entries from source
		for (const entry of sourceEntries) {
			if (entry.type !== "session") {
				appendFileSync(newSessionFile, `${JSON.stringify(entry)}\n`);
			}
		}

		return new SessionManager(resolvedTargetCwd, dir, newSessionFile, true);
	}

	/**
	 * List all sessions for a directory.
	 * @param cwd Working directory (used to compute default session directory)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.senpi/agent/sessions/<encoded-cwd>/).
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async list(cwd: string, sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]> {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const resolvedCwd = resolvePath(cwd);
		const sessions = (await listSessionsFromDir(dir, onProgress)).filter(
			(session) => !filterCwd || sessionCwdMatches(session.cwd, resolvedCwd),
		);
		sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
		return sessions;
	}

	/**
	 * List all sessions across all project directories.
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async listAll(onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(
		sessionDirOrOnProgress?: string | SessionListProgress,
		onProgress?: SessionListProgress,
	): Promise<SessionInfo[]> {
		const customSessionDir =
			typeof sessionDirOrOnProgress === "string" ? normalizePath(sessionDirOrOnProgress) : undefined;
		const progress = typeof sessionDirOrOnProgress === "function" ? sessionDirOrOnProgress : onProgress;
		if (customSessionDir) {
			const sessions = await listSessionsFromDir(customSessionDir, progress);
			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		}

		const sessionsDir = getSessionsDir();

		try {
			if (!existsSync(sessionsDir)) {
				return [];
			}
			const entries = await readdir(sessionsDir, { withFileTypes: true });
			const dirs = entries
				.filter((entry) => entry.isDirectory() || entry.isSymbolicLink())
				.map((entry) => join(sessionsDir, entry.name));

			// Count total files first for accurate progress
			let totalFiles = 0;
			const dirFiles: string[][] = [];
			for (const dir of dirs) {
				try {
					const files = (await readdir(dir)).filter((f) => f.endsWith(".jsonl"));
					dirFiles.push(files.map((f) => join(dir, f)));
					totalFiles += files.length;
				} catch {
					dirFiles.push([]);
				}
			}

			// Process all files with progress tracking
			let loaded = 0;
			const sessions = await listSessionInfos(dirFiles.flat(), () => {
				loaded++;
				progress?.(loaded, totalFiles);
			});

			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		} catch {
			return [];
		}
	}
}
